using RestaurantReservation.Db;

namespace RestaurantReservationApp.Invokers_SampleData.DBFunctionsInvokers
{
    public class DbFunctionsProceduresTest
    {
        private readonly RestaurantReservationDbContext _dbContext;
        public DbFunctionsProceduresTest(RestaurantReservationDbContext dbContext)
        {
            _dbContext = dbContext;
        }
        public void TestCalculateRestaurantTotalRevenue()
        {
            Console.WriteLine("\n\nTesting DB Function : Calculate the total revenue generated by a specific restaurant ...");
            int restaurantId = 2;
            decimal? totalRevenue = _dbContext.CalculateRestaurantTotalRevenue(restaurantId);
            Console.WriteLine($"Total revenue for restaurant with id {restaurantId} = {totalRevenue:C}");
        }
    }
}
